name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build .
    - name: ctest
      run: ctest
